[tool.poetry]
name = "sentinel-auth-vault"
version = "0.1.0"
description = "Enterprise-Grade Zero Trust Authentication & Autonomous Security Engine"
authors = ["Abdul Aziz"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.115.0"
uvicorn = "^0.30.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.35"}
alembic = "^1.13.3"
asyncpg = "^0.29.0"
pydantic-settings = "^2.5.2"
passlib = {extras = ["argon2"], version = "^1.7.4"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
redis = "^5.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
